# Generated by Django 6.0.3 on 2026-04-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('spirit', 'Destilado'), ('liqueur', 'Licor'), ('bitter', 'Bitter'), ('mixer', 'Mixer'), ('juice', 'Jugo'), ('fruit', 'Fruta / Verdura'), ('syrup', 'Jarabe'), ('garnish', 'Guarnición'), ('ice', 'Hielo'), ('other', 'Otro')], default='other', max_length=20)),
                ('in_stock', models.BooleanField(default=False, verbose_name='Disponible en mi bar')),
                ('is_low', models.BooleanField(default=False, verbose_name='Se está acabando')),
                ('add_to_shopping', models.BooleanField(default=False, verbose_name='Agregar a compra')),
                ('notes', models.TextField(blank=True)),
                ('substitutes', models.ManyToManyField(blank=True, related_name='can_replace_for', to='bar.ingredient', verbose_name='Reemplazos posibles')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('preparation', models.TextField(verbose_name='Preparación paso a paso')),
                ('personal_rating', models.PositiveSmallIntegerField(default=0, verbose_name='Nota personal (0-5)')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('visible_public', models.BooleanField(default=True, verbose_name='Visible en menú público')),
                ('tags', models.ManyToManyField(blank=True, to='bar.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unit', models.CharField(choices=[('oz', 'oz'), ('ml', 'ml'), ('dash', 'dash'), ('drop', 'gota'), ('piece', 'unidad'), ('slice', 'rodaja'), ('leaf', 'hoja'), ('top', 'top / completar'), ('other', 'otro')], default='oz', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('required', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('optional', models.BooleanField(default=False, verbose_name='Opcional')),
                ('allow_substitute', models.BooleanField(default=True, verbose_name='Permite reemplazo')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='bar.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='bar.ingredient')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('cocktail', 'ingredient', 'order')},
            },
        ),
    ]
