# Generated by Django 6.0.3 on 2026-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(help_text='Ej: menu-viernes', unique=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible públicamente')),
                ('cocktails', models.ManyToManyField(blank=True, related_name='collections', to='bar.cocktail')),
            ],
        ),
    ]
