# Generated by Django 6.0.3 on 2026-04-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_menucollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucollection',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Colección activa para QR'),
        ),
    ]
